export {
  assertPermissionScope,
  CONSENT_EVENT_TYPES,
  CONSENT_GRANT_STATUSES,
  CONSENT_PERMISSIONS,
  CONSENT_SCOPES,
  GRANTEE_TYPES,
  InvalidConsentScopeError,
  PERMITTED_SCOPES,
  SYSTEM_BASES,
  type ConsentBasis,
  type ConsentEventType,
  type ConsentGrantStatus,
  type ConsentPermission,
  type ConsentScope,
  type GranteeType,
  type SystemBasis,
} from './vocabulary.js';
export {
  assertTemplatePublished,
  ConsentTemplateNotPublishedError,
  consentTemplateVersionKey,
  createConsentTemplateVersion,
  findConsentTemplateVersion,
  publishConsentTemplateVersion,
  type ConsentTemplateStatus,
  type ConsentTemplateVersion,
} from './templates.js';
export {
  acceptTrustedContact,
  findTrustedContact,
  inviteTrustedContact,
  listTrustedCircle,
  membershipPermitsUse,
  setTrustedContactStatus,
  TRUSTED_CONTACT_STATUSES,
  TrustedContactChannelRequiredError,
  TrustedContactTerminalError,
  type InviteTrustedContactInput,
  type TrustedContact,
  type TrustedContactStatus,
} from './trusted-circle.js';
export {
  expireDueGrants,
  findActiveGrant,
  findConsentGrant,
  grantConsent,
  listConsentEvents,
  listGrantsForVeteran,
  recordConsentEvent,
  revokeConsent,
  type ConsentEventRecord,
  type ConsentGrant,
  type GrantConsentInput,
  type RecordConsentEventInput,
} from './grants.js';
export {
  ConsentDeniedError,
  evaluateDisclosure,
  requireDisclosure,
  type ConsentDecision,
  type ConsentEvaluationDeps,
  type DenialReason,
  type DisclosureRequest,
} from './evaluate.js';
